// Generated by reflectclient/wrap at 2016-12-17 22:10:31.615097493 +0000 UTC
package githubservicev3wrapper

import (
	"github.com/dforsyth/reflectclient-github"
	"github.com/dforsyth/reflectclient-github/models"
)

type GithubServiceV3Wrapper struct {
	service *github.GithubServiceV3
}

func (r *GithubServiceV3Wrapper) Repo(pos0 *github.RepoParams) (*models.Repo, error) {
	return r.service.Repo(pos0)
}

func (r *GithubServiceV3Wrapper) Repos(pos0 *github.ReposParams) ([]*models.Repo, error) {
	return r.service.Repos(pos0)
}

func (r *GithubServiceV3Wrapper) UserRepos(pos0 *github.UserReposParams) ([]*models.Repo, error) {
	return r.service.UserRepos(pos0)
}

func WrapGithubServiceV3(service *github.GithubServiceV3) *GithubServiceV3Wrapper {
	return &GithubServiceV3Wrapper{service}
}
