// Generated by jot version 0.0.0 on 2016-11-23 04:32:28.582007005 +0000 UTC

package models 

type User struct {
	Email             string                 `json:"email"`
	UpdatedAt         string                 `json:"updated_at"`
	Type              string                 `json:"type"`
	Collaborators     float64                `json:"collaborators"`
	GravatarId        string                 `json:"gravatar_id"`
	HtmlUrl           string                 `json:"html_url"`
	GistsUrl          string                 `json:"gists_url"`
	EventsUrl         string                 `json:"events_url"`
	Blog              string                 `json:"blog"`
	PublicGists       float64                `json:"public_gists"`
	OwnedPrivateRepos float64                `json:"owned_private_repos"`
	AvatarUrl         string                 `json:"avatar_url"`
	SubscriptionsUrl  string                 `json:"subscriptions_url"`
	SiteAdmin         bool                   `json:"site_admin"`
	Name              string                 `json:"name"`
	Location          string                 `json:"location"`
	Hireable          bool                   `json:"hireable"`
	Plan              map[string]interface{} `json:"plan"`
	FollowersUrl      string                 `json:"followers_url"`
	StarredUrl        string                 `json:"starred_url"`
	ReposUrl          string                 `json:"repos_url"`
	Followers         float64                `json:"followers"`
	Following         float64                `json:"following"`
	DiskUsage         float64                `json:"disk_usage"`
	FollowingUrl      string                 `json:"following_url"`
	PublicRepos       float64                `json:"public_repos"`
	TotalPrivateRepos float64                `json:"total_private_repos"`
	Url               string                 `json:"url"`
	ReceivedEventsUrl string                 `json:"received_events_url"`
	Bio               string                 `json:"bio"`
	CreatedAt         string                 `json:"created_at"`
	Login             string                 `json:"login"`
	OrganizationsUrl  string                 `json:"organizations_url"`
	Company           string                 `json:"company"`
	PrivateGists      float64                `json:"private_gists"`
	Id                float64                `json:"id"`
}
